/*
 * Ravi Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Ravi.Web.Api.Converters;

namespace Ravi.Web.Api.Models
{ 
        /// <summary>
        /// Gets or Sets HealthStatusEnumV1
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<HealthStatusEnumV1>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum HealthStatusEnumV1
        {
            
            /// <summary>
            /// Enum Healthy for Healthy
            /// </summary>
            [EnumMember(Value = "Healthy")]
            Healthy = 1,
            
            /// <summary>
            /// Enum Unhealthy for Unhealthy
            /// </summary>
            [EnumMember(Value = "Unhealthy")]
            Unhealthy = 2,
            
            /// <summary>
            /// Enum Degraded for Degraded
            /// </summary>
            [EnumMember(Value = "Degraded")]
            Degraded = 3
        }
}
