// <auto-generated>
/*
 * Ravi Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Ravi.Web.Client.Client;

namespace Ravi.Web.Client.Model
{
    /// <summary>
    /// Defines HealthStatusEnumV1
    /// </summary>
    public enum HealthStatusEnumV1
    {
        /// <summary>
        /// Enum Healthy for value: Healthy
        /// </summary>
        Healthy = 1,

        /// <summary>
        /// Enum Unhealthy for value: Unhealthy
        /// </summary>
        Unhealthy = 2,

        /// <summary>
        /// Enum Degraded for value: Degraded
        /// </summary>
        Degraded = 3
    }

    /// <summary>
    /// Converts <see cref="HealthStatusEnumV1"/> to and from the JSON value
    /// </summary>
    public static class HealthStatusEnumV1ValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="HealthStatusEnumV1"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static HealthStatusEnumV1 FromString(string value)
        {
            if (value.Equals("Healthy"))
                return HealthStatusEnumV1.Healthy;

            if (value.Equals("Unhealthy"))
                return HealthStatusEnumV1.Unhealthy;

            if (value.Equals("Degraded"))
                return HealthStatusEnumV1.Degraded;

            throw new NotImplementedException($"Could not convert value to type HealthStatusEnumV1: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="HealthStatusEnumV1"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static HealthStatusEnumV1? FromStringOrDefault(string value)
        {
            if (value.Equals("Healthy"))
                return HealthStatusEnumV1.Healthy;

            if (value.Equals("Unhealthy"))
                return HealthStatusEnumV1.Unhealthy;

            if (value.Equals("Degraded"))
                return HealthStatusEnumV1.Degraded;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="HealthStatusEnumV1"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(HealthStatusEnumV1 value)
        {
            if (value == HealthStatusEnumV1.Healthy)
                return "Healthy";

            if (value == HealthStatusEnumV1.Unhealthy)
                return "Unhealthy";

            if (value == HealthStatusEnumV1.Degraded)
                return "Degraded";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HealthStatusEnumV1"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class HealthStatusEnumV1JsonConverter : JsonConverter<HealthStatusEnumV1>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override HealthStatusEnumV1 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            HealthStatusEnumV1? result = rawValue == null
                ? null
                : HealthStatusEnumV1ValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the HealthStatusEnumV1 to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthStatusEnumV1"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, HealthStatusEnumV1 healthStatusEnumV1, JsonSerializerOptions options)
        {
            writer.WriteStringValue(HealthStatusEnumV1ValueConverter.ToJsonValue(healthStatusEnumV1).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HealthStatusEnumV1"/>
    /// </summary>
    public class HealthStatusEnumV1NullableJsonConverter : JsonConverter<HealthStatusEnumV1?>
    {
        /// <summary>
        /// Returns a HealthStatusEnumV1 from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override HealthStatusEnumV1? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            HealthStatusEnumV1? result = rawValue == null
                ? null
                : HealthStatusEnumV1ValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the HealthStatusEnumV1 to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthStatusEnumV1"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, HealthStatusEnumV1? healthStatusEnumV1, JsonSerializerOptions options)
        {
            writer.WriteStringValue(healthStatusEnumV1.HasValue ? HealthStatusEnumV1ValueConverter.ToJsonValue(healthStatusEnumV1.Value).ToString() : "null");
        }
    }
}
