// <auto-generated>
/*
 * Ravi Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Ravi.Web.Client.Client;

namespace Ravi.Web.Client.Model
{
    /// <summary>
    /// HealthCheckResponseV1
    /// </summary>
    public partial class HealthCheckResponseV1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HealthCheckResponseV1" /> class.
        /// </summary>
        /// <param name="server">server</param>
        /// <param name="database">database</param>
        /// <param name="status">status</param>
        /// <param name="description">description</param>
        /// <param name="exception">exception</param>
        /// <param name="timestamp">timestamp</param>
        [JsonConstructor]
        public HealthCheckResponseV1(Option<string?> server = default, Option<string?> database = default, Option<HealthStatusEnumV1?> status = default, Option<string?> description = default, Option<string?> exception = default, Option<DateTimeOffset?> timestamp = default)
        {
            ServerOption = server;
            DatabaseOption = database;
            StatusOption = status;
            DescriptionOption = description;
            ExceptionOption = exception;
            TimestampOption = timestamp;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<HealthStatusEnumV1?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public HealthStatusEnumV1? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Server
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ServerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Server
        /// </summary>
        [JsonPropertyName("server")]
        public string? Server { get { return this.ServerOption; } set { this.ServerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Database
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DatabaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Database
        /// </summary>
        [JsonPropertyName("database")]
        public string? Database { get { return this.DatabaseOption; } set { this.DatabaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Exception
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExceptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Exception
        /// </summary>
        [JsonPropertyName("exception")]
        public string? Exception { get { return this.ExceptionOption; } set { this.ExceptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Timestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> TimestampOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTimeOffset? Timestamp { get { return this.TimestampOption; } set { this.TimestampOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HealthCheckResponseV1 {\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("  Database: ").Append(Database).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Exception: ").Append(Exception).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HealthCheckResponseV1" />
    /// </summary>
    public class HealthCheckResponseV1JsonConverter : JsonConverter<HealthCheckResponseV1>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="HealthCheckResponseV1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HealthCheckResponseV1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> server = default;
            Option<string?> database = default;
            Option<HealthStatusEnumV1?> status = default;
            Option<string?> description = default;
            Option<string?> exception = default;
            Option<DateTimeOffset?> timestamp = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "server":
                            server = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "database":
                            database = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<HealthStatusEnumV1?>(HealthStatusEnumV1ValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "exception":
                            exception = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class HealthCheckResponseV1.");

            return new HealthCheckResponseV1(server, database, status, description, exception, timestamp);
        }

        /// <summary>
        /// Serializes a <see cref="HealthCheckResponseV1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthCheckResponseV1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HealthCheckResponseV1 healthCheckResponseV1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, healthCheckResponseV1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HealthCheckResponseV1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="healthCheckResponseV1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HealthCheckResponseV1 healthCheckResponseV1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (healthCheckResponseV1.ServerOption.IsSet)
                if (healthCheckResponseV1.ServerOption.Value != null)
                    writer.WriteString("server", healthCheckResponseV1.Server);
                else
                    writer.WriteNull("server");

            if (healthCheckResponseV1.DatabaseOption.IsSet)
                if (healthCheckResponseV1.DatabaseOption.Value != null)
                    writer.WriteString("database", healthCheckResponseV1.Database);
                else
                    writer.WriteNull("database");

            if (healthCheckResponseV1.StatusOption.IsSet)
            {
                var statusRawValue = HealthStatusEnumV1ValueConverter.ToJsonValue(healthCheckResponseV1.Status!.Value);
                writer.WriteString("status", statusRawValue);
            }
            if (healthCheckResponseV1.DescriptionOption.IsSet)
                if (healthCheckResponseV1.DescriptionOption.Value != null)
                    writer.WriteString("description", healthCheckResponseV1.Description);
                else
                    writer.WriteNull("description");

            if (healthCheckResponseV1.ExceptionOption.IsSet)
                if (healthCheckResponseV1.ExceptionOption.Value != null)
                    writer.WriteString("exception", healthCheckResponseV1.Exception);
                else
                    writer.WriteNull("exception");

            if (healthCheckResponseV1.TimestampOption.IsSet)
                if (healthCheckResponseV1.TimestampOption.Value != null)
                    writer.WriteString("timestamp", healthCheckResponseV1.TimestampOption.Value!.Value.ToString(TimestampFormat));
                else
                    writer.WriteNull("timestamp");
        }
    }
}
