/*
 * Ravi Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Ravi.Web.Api.Attributes;
using Ravi.Web.Api.Models;

namespace Ravi.Web.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class HealthCheckApiController : ControllerBase
    { 
        /// <summary>
        /// Health Check API
        /// </summary>
        /// <response code="200">Successful operation</response>
        [HttpGet]
        [Route("/api/v1/health-check")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(HealthCheckResponseV1))]
        public abstract Task<IActionResult> HealthCheckV1();
    }
}
